services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.7
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr
      - INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
      - --pandaproxy-addr
      - 0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - localhost:8082
    ports:
      - "9092:9092"
      - "8082:8082"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.4.5
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8090:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
